spring:
  application:
    name: gateway-zuul
server:
  port: 7600
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
zuul:
  routes:
    user-register: /user/**
#      /userlogin->/user/userlogin
    #seller related service

    sellers: /seller/**
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie

